name: Dependabot for Nuget dependencies and Github Actions
version: 2
updates:
  # Update to newer version of GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

 # don't do nuget here, WPF does not build correctly on linux
# to work on FSharp.Core too the fsproj needs : <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
# and <PackageReference Include="FSharp.Core" Version= ...
# see https://github.com/dependabot/dependabot-core/issues/10883
# - package-ecosystem: "nuget"
#   directory: "/"
#   schedule:
#     interval: "daily"
