namespace Fesh

open System
open System.Windows
open System.IO
open System.Drawing

open Fesh.Model
open Fesh.Util
open Fesh.Config
open System.Text

(**
Opus 5.5:
I added TODO comments for the remaining issues and committed everything as `cd2cefa` on the `private` branch. The build still has 0 warnings and 0 errors. I haven't pushed.

Each TODO sits next to the code it's about in [CompileScript.fs](Src/CompileScript.fs):
- **`toCamelCase`:** some file names give an invalid namespace or file name, like `Script (1)` or a name starting with a digit. An empty name throws.
- **`replace`:** it duplicates `Str.replace`.
- **Loaded files:** a loaded file without its own `module` or `namespace` line still fails with FS0222.
- **Other script-only directives:** `#I`, `#i`, `#time`, `#help` and `#quit` are still left in the generated file.
- **The added `namespace` line:** scripts that start with their own `module` or `namespace`, or have top-level `let`s, fail without a clear compiler error.
- **`overWriteExisting`:** it should return `Async<bool>` instead of calling `RunSynchronously`, and answering "No" logs nothing. I also corrected its comment from "1h" to "half an hour" to match the code.
- **XML:** names and paths aren't escaped, so an `&` breaks the project file.
- **`getRefsXml`:** it copies files as a hidden side effect while building the XML.
- **`getFsxXml`:** loaded files with the same name from different folders overwrite each other.
- **`compileScript`:**
  - Nothing stops a second compile of the same script while one is running.
  - The script name is stripped of `.fsx` case-sensitively.
  - The output folders are created even if the user declines.
  - After the `#r` from the clipboard is run in Fesh, the DLL stays locked, so the next recompile fails with MSB3027 until Fesh restarts.

I didn't add a CHANGELOG entry. Tell me if this change should have one.
**)

module CompileScript =

    /// also removes "_" ;  "-" ; "+"; "|"; " " from string
    /// first letter will be capital
    let toCamelCase (s:string) =
        // TODO the result is used as namespace and file name, but is not always a valid identifier:
        // "Script (1)" gives "script(1)", "2024-beam" gives "2024Beam" (leading digit). Keep only letters and digits, prefix "_" if it starts with a digit.
        // TODO s.[0] throws on an empty string, and the result is empty if s has only separators
        s.Split([|"_" ;  "-" ; "+"; "|"; " "|], StringSplitOptions.RemoveEmptyEntries) // keep dot?!
        |> Array.map Str.up1
        |> String.concat ""
        |> (fun x -> if Char.IsLower s.[0] then Str.low1 x else x)

    let replace (a:string) (b:string) (s:string) = s.Replace(a,b) // TODO duplicate of Str.replace

    type DllRef = {fullPath:string option; fileName:string; nameNoExt:string; copyLocal:bool}
    /// code is the content of the loaded file with its #r and #load lines commented out
    type FsxRef = {fullPath:string; fileName:string; code:string}
    type NugetRef = {name:string; version:string}

    /// Resolves a path from a #r or #load line against the folder of the file that contains it, like FSI does.
    /// (Path.Combine returns the second path unchanged if it is already absolute.)
    let resolvePath (dir:string) (path:string) =
        Path.GetFullPath(Path.Combine(dir, path)).Replace('\\','/')

    /// Comments out all #r and #load lines and collects what they reference.
    /// Files from #load are processed recursively too.
    /// They are added to the fsx list before the file that loads them, so they compile first.
    let extractRefs(code:string, scriptPath:string, nameSpace:string) : ResizeArray<DllRef>*ResizeArray<FsxRef>*ResizeArray<NugetRef>*string=
        let refs = ResizeArray<DllRef>()
        let nugs = ResizeArray<NugetRef>()
        let fsxs = ResizeArray<FsxRef>()
        let visited = Collections.Generic.HashSet<string>(StringComparer.OrdinalIgnoreCase) // to load each file only once, and to avoid cycles
        visited.Add (Path.GetFullPath(scriptPath).Replace('\\','/')) |> ignore

        let addRef (r:DllRef) =
            if not (refs.Exists(fun x -> x.fileName.Equals(r.fileName, StringComparison.OrdinalIgnoreCase))) then refs.Add r
        let addNug (n:NugetRef) =
            match nugs.FindIndex(fun x -> x.name.Equals(n.name, StringComparison.OrdinalIgnoreCase)) with
            | -1 -> nugs.Add n
            | i  -> if nugs[i].version = "*" then nugs[i] <- n // prefer an explicit version over the floating one

        let rec processCode (code:string, dir:string, header:string option) : string =
            let codeWithoutRefs = StringBuilder()
            codeWithoutRefs.AppendLine "// This file is generated by Fesh. Manual edits will get lost when regenerated." |> ignore
            header |> Option.iter (fun h -> codeWithoutRefs.AppendLine h |> ignore)
            for ln in code.Split('\n') do
                let tln = ln.Trim()
                if tln.StartsWith "#r \"nuget" then
                    codeWithoutRefs.Append "// "  |> ignore
                    match Str.between "nuget:" "\"" tln with
                    |None -> ()
                    |Some pkgV ->
                        let pkg,version =
                            if pkgV.Contains(",")then       pkgV |> Str.splitOnce ","
                            else                            pkgV, "*"
                        addNug {name=pkg.Trim(); version=version.Trim()}

                elif tln.StartsWith "#r " then
                    codeWithoutRefs.Append "// "  |> ignore
                    let _,path,_ = Str.splitTwice "\""  "\"" tln // get part in quotes
                    if path <> "" then
                        let stPath = path.Replace ('\\','/')
                        if stPath.Contains "/RhinoCommon.dll" then
                            addRef {fullPath= Some (resolvePath dir path); fileName="RhinoCommon.dll" ;nameNoExt="RhinoCommon"  ;  copyLocal=false}

                        elif stPath.Contains "/" || File.Exists(Path.Combine(dir, path)) then // a path, or a dll next to the script
                            let fileName = Path.GetFileName path
                            let nameNoExt = fileName.Replace(".dll", "") // TODO make case insensitive, cover .exe
                            addRef { fullPath=Some (resolvePath dir path); fileName=fileName ;nameNoExt=nameNoExt; copyLocal=true}
                        else
                            let nameNoExt = path.Replace(".dll", "") // TODO make case insensitive, cover .exe
                            addRef { fullPath=None; fileName=path ;nameNoExt=nameNoExt; copyLocal=false} // for BCL dlls of the .Net framework

                elif tln.StartsWith "#load " then
                    codeWithoutRefs.Append "// "  |> ignore
                    let _,path,_ = Str.splitTwice "\""  "\"" tln
                    if path <> "" then
                        let fullPath = resolvePath dir path
                        if visited.Add fullPath then
                            // TODO loaded files get no header, so one without its own top level 'module' or 'namespace' line fails with FS0222
                            let loadedCode = processCode (File.ReadAllText fullPath, Path.GetDirectoryName fullPath, None)
                            fsxs.Add {fullPath=fullPath; fileName=Path.GetFileName fullPath; code=loadedCode}

                // TODO other script only directives are not commented out yet: #I (then a bare #r "Foo.dll" from that folder is unresolved), #i "nuget:...", #time, #help, #quit

                codeWithoutRefs.AppendLine (ln.TrimEnd()) |> ignore
            codeWithoutRefs.ToString()

        // TODO because of this namespace line, scripts that start with their own top level 'module' or 'namespace', or have top level 'let's, fail to compile.
        // The compiler error does not say why. Detect a leading 'module' or 'namespace' line and skip the header, or log a hint.
        let mainCode = processCode (code, Path.GetDirectoryName scriptPath, Some $"namespace {nameSpace}")
        refs, fsxs, nugs, mainCode

    //if last write is more than half an hour ago ask for overwrite permissions
    // TODO this is called from inside an async, so return Async<bool> and use let! instead of Async.RunSynchronously
    // TODO when the user answers No nothing is logged, log that the compilation was skipped
    let overWriteExisting fsProj :bool=
        async{
            do! Async.SwitchToContext Fittings.SyncWpf.context
            let maxAgeHours = 0.5
            let fi = FileInfo(fsProj)
            return
                if fi.Exists then
                    let age = DateTime.UtcNow - fi.LastWriteTimeUtc
                    if age > (TimeSpan.FromHours maxAgeHours) then
                        let msg = sprintf "Do you want to recompile and overwrite the existing files?\r\n \r\n%s\r\n \r\nthat are %.2f days old at\r\n \r\n(This dialog only shows if the last compilation was more than %.1f hours ago.)"fi.FullName age.TotalDays  maxAgeHours
                        //match MessageBox.Show(msg, StyleState.dialogCaption, MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation, MessageBoxDefaultButton.Button2) with  // uses Windows.Forms
                        match MessageBox.Show(
                            IEditor.mainWindow,
                            msg,
                            "Fesh | Recompile and overwrite?",
                            MessageBoxButton.YesNo,
                            MessageBoxImage.Exclamation,
                            MessageBoxResult.No,// default result
                            MessageBoxOptions.None) with
                        | MessageBoxResult.Yes-> true
                        | MessageBoxResult.No-> false
                        | _ -> false
                    else
                        true
                else
                    true
        }|>  Async.RunSynchronously

    // TODO getNugsXml and getRefsXml do not XML-escape names and paths, an '&' in a dll file name or in the RhinoCommon path gives MSB4025. Use SecurityElement.Escape.
    let getNugsXml (nugs:ResizeArray<NugetRef>) : string =
           seq{ for nug in nugs  do  "<PackageReference Include=\"" + nug.name + "\" Version=\"" + nug.version + "\" />" }
           |> String.concat (Environment.NewLine  + String(' ',4) )

    /// Also copies the dlls with copyLocal=true to the lib folder.
    /// TODO the copying happens lazily, inside the seq consumed by String.concat. Do it in a separate step before building the XML.
    let getRefsXml (libFolderFull:string,  refs:ResizeArray<DllRef>) : string=
        seq{
            for ref in refs |> Seq.sortBy (fun r -> if r.fullPath.IsNone then 0 else 1) do
                match ref.fullPath with
                | None -> // for BCL dlls of the .Net framework
                    "<Reference Include=\"" + ref.nameNoExt + "\" />"
                |Some fPath ->
                    if ref.copyLocal then
                        let newp = IO.Path.Combine(libFolderFull, ref.fileName)
                        if IO.File.Exists newp then IO.File.Delete newp
                        IO.File.Copy(fPath,newp )

                        let xml  = Path.ChangeExtension(fPath,"xml")
                        let xmln = Path.ChangeExtension(newp,"xml")
                        if IO.File.Exists xmln then IO.File.Delete xmln
                        if IO.File.Exists (xml) then IO.File.Copy(xml, xmln)

                        let pdb  = Path.ChangeExtension(fPath,"pdb")
                        let pdbn = Path.ChangeExtension(newp,"pdb")
                        if IO.File.Exists pdbn then IO.File.Delete pdbn
                        if IO.File.Exists (pdb) then IO.File.Copy(pdb, pdbn)
                        "<Reference Include=\"" + ref.nameNoExt + "\"><HintPath>" + ScriptCompilerFsproj.LibFolderName + "/" + ref.fileName + "</HintPath></Reference>"

                    else
                        "<Reference Include=\"" + ref.nameNoExt + "\"><HintPath>" + fPath + "</HintPath><Private>False</Private></Reference>"
        }
        |> String.concat (Environment.NewLine  + String(' ',4) )

    let getFsxXml (projFolder:string, nameSpace:string, code:string, fsxloads:ResizeArray<FsxRef>) : string=
        seq{
            for load in fsxloads do
                // TODO two loaded files with the same name from different folders overwrite each other here, and could also collide with the main {nameSpace}.fs
                let niceName = (Path.GetFileNameWithoutExtension load.fileName |> toCamelCase  ) + ".fs"
                IO.File.WriteAllText(IO.Path.Combine(projFolder,niceName), load.code, Text.Encoding.UTF8)
                yield "<Compile Include=\"" + niceName + "\" />"

            let fsxName = nameSpace + ".fs"
            let fsxPath = IO.Path.Combine(projFolder,fsxName)
            IO.File.WriteAllText(fsxPath,code,Text.Encoding.UTF8)
            yield     "<Compile Include=\"" + fsxName + "\" />"
        }
        |> String.concat (Environment.NewLine + String(' ',4) )


    //TODO  use https://github.com/Tyrrrz/CliWrap ??

    let green  msg = IFeshLog.log.PrintfnColor 0   140 0 msg
    let black  msg = IFeshLog.log.PrintfnColor 0   0   0 msg
    let gray   msg = IFeshLog.log.PrintfnColor 190 190 190 msg
    //let gray msg = IFeshLog.log.PrintfColor  190 190 190 msg

    /// Asks vswhere.exe for the MSBuild.exe of the newest Visual Studio or Build Tools.
    /// vswhere.exe is installed with every Visual Studio since 2017, at a fixed location.
    let findMSBuildViaVsWhere () : string option =
        let vsWhere = Path.Combine(Environment.GetFolderPath Environment.SpecialFolder.ProgramFilesX86, "Microsoft Visual Studio", "Installer", "vswhere.exe")
        if not (File.Exists vsWhere) then
            None
        else
            try
                let psi = Diagnostics.ProcessStartInfo(vsWhere, @"-latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe -utf8")
                psi.UseShellExecute <- false
                psi.CreateNoWindow <- true
                psi.RedirectStandardOutput <- true
                psi.StandardOutputEncoding <- Encoding.UTF8
                use p = Diagnostics.Process.Start psi
                let output = p.StandardOutput.ReadToEnd()
                p.WaitForExit()
                output.Split([|'\r'; '\n'|], StringSplitOptions.RemoveEmptyEntries)
                |> Array.tryFind File.Exists
            with _ ->
                None

    let msBuild(psi:Diagnostics.ProcessStartInfo, fsProj, config:Config.Config) =
        gray "starting MSBuild.exe ..."
        let fromSettings = config.Settings.TryGetString "MSBuild.exe" |> Option.defaultValue ""
        let knownPaths = // fallback in case vswhere.exe is missing
            [
            @"C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
            @"C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe"
            @"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
            @"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe"
            @"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
            @"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
            ]
        let found =
            if File.Exists fromSettings then
                Some fromSettings
            else
                match findMSBuildViaVsWhere() with
                | Some exe -> Some exe
                | None     -> knownPaths |> List.tryFind File.Exists

        match found with
        | None ->
            IFeshLog.log.PrintfnIOErrorMsg  "MSBuild.exe not found via vswhere.exe nor at:\r\n%s " (knownPaths |> String.concat Environment.NewLine)
            IFeshLog.log.PrintfnIOErrorMsg  "If you have MSBuild.exe on your PC please add the path to the settings file like this:"
            IFeshLog.log.PrintfnAppErrorMsg "MSBuild.exe=C:/Folder/Where/it/is/MSBuild.exe"
            IFeshLog.log.PrintfnIOErrorMsg  "the settings file is at %s" config.RunContext.SettingsFileInfo.FullName
            false
        | Some msBuildexe ->
            psi.FileName <- "\"" + msBuildexe + "\""
            psi.Arguments <- String.concat " " ["\"" + fsProj + "\"" ;  "-restore" ] //; "/property:Configuration=Release"] configuration should be specified in the fsproj file
            true


    let dotnetBuild(psi:Diagnostics.ProcessStartInfo, fsProj)=
        // TODO check if dotnet sdk is installed
        gray "starting dotnet build ..."
        psi.FileName <- "dotnet"
        psi.Arguments <- String.concat " " ["build"; "\"" + fsProj + "\""  ] //;  "--configuration Release"] configuration is part of fsproj file
        true

    // TODO nothing prevents starting a second compilation of the same script while the first one is still running
    let compileScript(code, fp:FilePath, useMSBuild, config:Config) =
        match fp with
        |Deleted _ | NotSet _ -> IFeshLog.log.PrintfnAppErrorMsg "Cannot compile an unsaved or deleted script. Save it first"
        | SetTo fi ->
            async{
                try
                    gray "compiling %s ..." fi.Name
                    let fileName = fi.Name.Replace(".fsx","") // TODO use Path.GetFileNameWithoutExtension, this is case sensitive
                    let nameSpace = fileName |> toCamelCase
                    let outLiteral = "  " + nameSpace + " -> "
                    let mutable resultDll = "" // found via matching on outLiteral below
                    let folderName = "_compiled_" + nameSpace
                    let projFolder = IO.Path.Combine(fi.DirectoryName,folderName)
                    let libFolderFull = IO.Path.Combine(projFolder, ScriptCompilerFsproj.LibFolderName)
                    // TODO the folders get created even if the user declines in overWriteExisting below. The second call is redundant, the first one creates projFolder too.
                    IO.Directory.CreateDirectory(libFolderFull)  |> ignore
                    IO.Directory.CreateDirectory(projFolder)  |> ignore
                    let fsProj = IO.Path.Combine(projFolder,nameSpace + ".fsproj")
                    if overWriteExisting fsProj then
                        let refs, fsxs, nugs, codeWithoutRefs = extractRefs (code, fi.FullName, nameSpace)
                        let fsxXml = getFsxXml(projFolder, nameSpace ,codeWithoutRefs, fsxs)
                        let refXml = getRefsXml(libFolderFull,refs)
                        let nugXml = getNugsXml(nugs)
                        config.ScriptCompilerFsproj.Get()
                        |> replace "{rootNamespace}" nameSpace
                        |> replace "{assemblyName}" nameSpace
                        |> replace "{version}" ScriptCompilerFsproj.AssemblyVersionToWrite
                        |> replace "{nuget-packages}" nugXml
                        |> replace "{dll-file-references}" refXml
                        |> replace "{code-files}" fsxXml
                        |> fun s ->
                            IO.File.WriteAllText(fsProj,s,Text.Encoding.UTF8)
                            gray "project files created at %s" fsProj
                            //https://stackoverflow.com/questions/1145969/processinfo-and-redirectstandardoutput
                            let psi = new System.Diagnostics.ProcessStartInfo()
                            let compilerExists =
                                if useMSBuild then msBuild     ( psi, fsProj, config)
                                else               dotnetBuild ( psi, fsProj)
                            if compilerExists then
                                IFeshLog.log.PrintfnColor 0 0 200 "%s %s" psi.FileName psi.Arguments
                                psi.UseShellExecute <- false
                                psi.CreateNoWindow <- true //true if the process should be started without creating a new window to contain it
                                psi.RedirectStandardError <-true
                                psi.RedirectStandardOutput <-true

                                let enc =
                                    // Text.Encoding.GetEncoding(Globalization.CultureInfo.CurrentCulture.TextInfo.OEMCodePage) // original version
                                    // CodePagesEncodingProvider.Instance.GetEncoding(Globalization.CultureInfo.CurrentCulture.TextInfo.OEMCodePage) // stackoverflow version
                                    Encoding.UTF8
                                // https://stackoverflow.com/questions/56802715/firefoxwebdriver-no-data-is-available-for-encoding-437
                                // <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
                                // for console also see https://stackoverflow.com/a/1427817/969070
                                // https://stackoverflow.com/a/48436394/969070
                                psi.StandardOutputEncoding <- enc
                                psi.StandardErrorEncoding  <- enc

                                use p = new Diagnostics.Process()
                                p.StartInfo <- psi
                                p.OutputDataReceived.Add ( fun d ->
                                    let txt = d.Data
                                    if not <| isNull txt then // happens often actually
                                        if   txt.Contains "Build FAILED." then      IFeshLog.log.PrintfnColor 220 0 150  "%s" txt
                                        elif txt.Contains "error FS"   then         IFeshLog.log.PrintfnColor 220 0 0  "%s" txt
                                        elif txt.Contains "Build succeeded." then   green  "%s" txt
                                        elif txt.Contains outLiteral  then
                                            resultDll <- txt.Replace(outLiteral,"").Trim()
                                            gray "%s" txt
                                        else
                                            gray "%s" txt
                                        )
                                p.ErrorDataReceived.Add (  fun d -> if not <| isNull d.Data then IFeshLog.log.PrintfnAppErrorMsg "%s" d.Data) // Data is null at the end of the stream
                                p.Start() |> ignore
                                p.BeginOutputReadLine()
                                p.BeginErrorReadLine()
                                //log.PrintfnInfoMsg "compiling to %s" (IO.Path.Combine(projFolder,"bin","Release","netstandard2.0",nameSpace+".dll"))
                                p.WaitForExit() // without a timeout this also waits until all redirected output is received, so resultDll is set by now.
                                // Don't use the Process.Exited event for this, it can fire before the last output lines are received.
                                // TODO once this #r is evaluated in the in-process FSI, the dll stays locked until Fesh restarts (assemblies can't be unloaded),
                                // so the next recompile fails with MSB3027. Mention this in the message, or build to a versioned output path.
                                if resultDll <> "" then
                                    gray  "*build done! This line is copied to your clipboard, paste via Ctrl + V :"
                                    IFeshLog.log.PrintfColor  190 0 50 "#r @\""
                                    IFeshLog.log.PrintfColor  0 0 0 "%s" resultDll
                                    IFeshLog.log.PrintfnColor 190 0 50 "\""
                                    Fittings.SyncWpf.doSync ( fun () ->
                                        try Clipboard.SetText("#r @\"" + resultDll + "\"\r\n") // can fail if another app has the clipboard open
                                        with e -> IFeshLog.log.PrintfnAppErrorMsg "Could not copy to the clipboard: %s" e.Message )
                                else
                                    gray  "*build process ended!"
                                gray "--------------------------------------------------------------------------------"

                with
                    e -> IFeshLog.log.PrintfnAppErrorMsg "%A" e
            } |> Async.Start



