name: Check Links

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 6 * * 6'

# The repo default for GITHUB_TOKEN is read/write. Checking links only needs to read the code.
permissions:
  contents: read

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: JustinBeckwith/linkinator-action@36a0bfbfecd5e237e8f8531537a693616c505faf # v2.4.5
        with:
          paths: README.md CHANGELOG.md
