name: Check Links

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 6 * * 6'

# The repo default for GITHUB_TOKEN is read/write. Checking links only needs to read the code.
permissions:
  contents: read

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: JustinBeckwith/linkinator-action@12f7a61a56e5e75d659f0dfd6357e2d852ede281 # v2.5.0
        with:
          paths: README.md CHANGELOG.md
