name: Build and Release Standalone

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: dotnet build FeshStandalone.fsproj --configuration Release

    - name: Create zip file
      run: |
        powershell Compress-Archive -Path bin/standalone/* -DestinationPath bin/standalone/standalone.zip    
    
    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2.2.3
      with:
        version: ${{ github.ref }}
        path: ./CHANGELOG.md

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref_name}}
        release_name: Fesh ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
            > [!IMPORTANT]
            > Don't forget to **unblock** the zip file before extracting.  

            After extracting save at any location and just run `Fesh.exe` to start.

            Changes:   
            ${{ steps.changelog_reader.outputs.changes }}

            [Full Changelog](https://github.com/goswinr/Fesh/blob/main/CHANGELOG.md)
            

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin/standalone/standalone.zip
        asset_name: standalone.zip
        asset_content_type: application/zip